site_name: Byzantine Protocol
repo_url: https://github.com/somethingdarkside1/Byzantine-Protocol/
site_url: https://byzantineprotocol.com/
repo_name: Byzantine Protocol Github
site_author: Vitali Liouti
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes 
    - navigation.top
    - toc.follow
    - toc.integrate
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - search.share
extra_css:
  - extra.css
plugins:
  - search
  - meta
  - social
  - privacy
  - tags
  - table-reader
  - autolinks 
  - bootstrap-tables
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - tables
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md