site_name: BYZANTINE PROTOCOL
repo_url: https://github.com/somethingdarkside1/Byzantine-Protocol/
site_url: https://byzantineprotocol.com/
repo_name: Official Github
copyright: Copyright &copy; 2025 Vitali Liouti
site_author: Vitali Liouti
theme:
  name: material
  logo: images/logo2.svg
  favicon: images/logo2.svg
  palette:
    scheme: slate
    primary: purple
    accent: pink
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - meta-descriptions
    - navigation.indexes 
    - navigation.top
    - navigation.footer
    - toc.follow
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - search.share
extra_css:
  - includes/extra.css
plugins:
  - search
  - social
  - tags
  - autorefs
  - glightbox
  - table-reader
  - bootstrap-tables
  - enumerate-headings:
    toc_depth: 0
    strict: false
    increment_across_pages: true
    include:
      - "*"
    exclude:
      - index.md
      - home.md
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.smartsymbols
  - pymdownx.blocks.caption
  - tables
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/somethingdarkside1/Byzantine-Protocol/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/v1tali.bsky.social
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@thev1tali
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/thev1tali/
    - icon: material/home
      link: https://v1tali.com/
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: French
      link: /fr/
      lang: fr
    - name: Deutch
      link: /de/
      lang: de
watch:
  - docs
  - docs/includes
nav:
  - Home: index.md
  - Game Overview:
    - game-overview/index.md
    - Game Summary: game-overview/summary.md
    - Core Pillars: game-overview/core-pillars.md
    - Game Flow: game-overview/game-flow.md
  - Setting & Narrative:
    - lore/index.md
    - Alternative History: lore/alternative-history.md
    - Three Powers Structure: lore/lore.md
    - Timeline: lore/timeline.md
  - Core Mechanics:
    - core-mechanics/index.md
    - Resource System: game-mechanics/resource-system.md
    - Research: game-mechanics/research-system.md
    - Victory Conditions: game-mechanics/victory-conditions.md
    - Wonders: game-mechanics/wonders.md
    - Crises: game-mechanics/crises.md
  - Game Setup:
    - game-setup/index.md
    - Turn Structure: game-setup/turn-structure.md
  - Cards:
    - cards/index.md
    - Card Mechanics: cards/mechanics.md
    - Card Types: cards/card-types.md
    - Technology Cards: cards/technology-cards.md
    - Humanity Cards: cards/humanity-cards.md
    - Reality Cards: cards/reality-cards.md
    - Event Cards: cards/event-cards.md
    - Card Database: cards/card-database.md
  - Factions:
    - factions/index.md
    - New Roman Empire: factions/new-roman-empire.md
    - Frankish Union: factions/frankish-union.md
    - Hanseatic League: factions/hanseatic-league.md
  - Characters:
    - characters/index.md
    - NRE Characters: characters/new-roman-empire-characters.md
  - Appendix:
    - Term Glossary: appendix/glossary.md