site_name: Byzantine Protocol
repo_url: https://github.com/somethingdarkside1/Byzantine-Protocol/
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes 
    - navigation.top
    - toc.follow
    - toc.integrate
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - search.share
extra_css:
  - extra.css
plugins:
  - search
  - table-reader
  - autolinks 
  - bootstrap-tables
