site_name: Byzantine Protocol
repo_url: https://github.com/somethingdarkside1/Byzantine-Protocol/
site_url: https://byzantineprotocol.com/
repo_name: Byzantine Protocol Github
site_author: Vitali Liouti
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes 
    - navigation.top
    - navigation.footer
    - toc.follow
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - search.share
extra_css:
  - includes/extra.css
plugins:
  - search
  - social
  - privacy
  - tags
  - table-reader
  - autolinks 
  - bootstrap-tables
  - minify_html:
      do_not_minify_doctype: true
      ensure_spec_compliant_unquoted_attribute_values: true
      keep_closing_tags: false
      keep_html_and_head_opening_tags: false
      keep_spaces_between_attributes: true
      keep_comments: false
      keep_input_type_text_attr: true
      keep_ssi_comments: false
      preserve_brace_template_syntax: false
      preserve_chevron_percent_template_syntax: false
      minify_css: true
      minify_js: true
      remove_bangs: false
      remove_processing_instructions: false
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - tables
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/somethingdarkside1/Byzantine-Protocol/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/v1tali.bsky.social
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@thev1tali
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/thev1tali/
    - icon: material/home
      link: https://v1tali.com/
    