site_name: Byzantine Protocol
repo_url: https://github.com/somethingdarkside1/Byzantine-Protocol/
repo_name: Byzantine Protocol Github
site_url: https://byzantineprotocol.com/
site_author: Vitali Liouti
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes 
    - navigation.top
    - toc.follow
    - toc.integrate
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - search.share
plugins:
  - search
  - table-reader
  - autolinks 
  - bootstrap-tables
