site_name: BYZANTINE PROTOCOL
repo_url: https://github.com/somethingdarkside1/Byzantine-Protocol/
site_url: https://byzantineprotocol.com/
repo_name: Official Github
site_description: The official site of the Byzantine Protocol RPG game
docs_dir: docs
copyright: Copyright &copy; 2025 Vitali Liouti
site_author: Vitali Liouti
theme:
  name: material
  logo: images/logo2.svg
  favicon: images/logo2.svg
  palette:
    scheme: slate
    primary: purple
    accent: pink
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes 
    - navigation.top
    - navigation.expand
    - navigation.footer
    - navigation.sections
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - meta-descriptions
extra_css:
  - other/extra.css
plugins:
  - search
  - social
  - tags
  - literate-nav:
      nav_file: summary.md
  - table-reader
  - enumerate-headings:
      toc_depth: 0
      strict: false
      increment_across_pages: true
      include:
        - "*"
      exclude:
        - home.md
        - SUMMARY.md
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      css_files:
        - other/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.smartsymbols
  - pymdownx.blocks.caption
  - tables
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.snippets:
      auto_append:
        - other/abbreviations.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/somethingdarkside1/Byzantine-Protocol/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/v1tali.bsky.social
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@thev1tali
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/thev1tali/
    - icon: fontawesome/solid/swatchbook
      link: https://v1tali.com/
