site_name: Byzantine Protocol
repo_url: https://github.com/somethingdarkside1/Byzantine-Protocol/
site_url: https://byzantineprotocol.com/
repo_name: Official Github
site_author: Vitali Liouti
theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - meta-descriptions
    - navigation.indexes 
    - navigation.top
    - navigation.footer
    - toc.follow
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - search.share
extra_css:
  - includes/extra.css
plugins:
  - search
  - social
  - tags
  - awesome-pages
  - autorefs
  - glightbox
  - table-reader
  - bootstrap-tables
  - enumerate-headings
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - tables
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/somethingdarkside1/Byzantine-Protocol/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/v1tali.bsky.social
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@thev1tali
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/thev1tali/
    - icon: material/home
      link: https://v1tali.com/
nav:
  - Home: index.md
  - 1. Game Overview:
    - Game Summary: game-overview/summary.md
    - Core Pillars: game-overview/core-pillars.md
    - Game Flow: game-overview/game-flow.md
  - 2. Setting & Narrative:
    - World Overview: lore/index.md
    - Alternative History: lore/alternative-history.md
    - Three Powers Structure: lore/lore.md
    - Timeline: lore/timeline.md
  - 3. Core Mechanics:
    - Resource System: game-mechanics/resource-system.md
    - Research: game-mechanics/research-system.md
    - Victory Conditions: game-mechanics/victory-conditions.md
    - Wonders: game-mechanics/wonders.md
    - Crises: game-mechanics/crises.md
  - 4. Game Setup:
    - Initial Setup: game-mechanics/initial-setup.md
    - Turn Structure: game-mechanics/turn-structure.md
  - 5. Cards:
    - Card Mechanics: cards/mechanics.md
    - Card Types: cards/card-types.md
    - Technology Cards: cards/technology-cards.md
    - Humanity Cards: cards/humanity-cards.md
    - Reality Cards: cards/reality-cards.md
    - Event Cards: cards/event-cards.md
    - Card Database: cards/card-database.md
  - 6. Factions:
    - New Roman Empire: factions/new-roman-empire.md
    - Frankish Union: factions/frankish-union.md
    - Hanseatic League: factions/hanseatic-league.md
  - 7. Characters:
    - NRE Characters: characters/new-roman-empire-characters.md
  - 8. Appendix:
    - Term Glossary: appendix/glossary.md